site_name: Python Project Generation Tool
site_url: https://pymaker.seapagan.net/

theme:
  name: material
  palette:
    primary: light-blue
    accent: blue
  features:
    - navigation.footer
    - navigation.expand
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/seapagan/py-maker
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/gnramsay_dev

copyright: © 2023 Grant Ramsay (Seapagan)

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - mkdocstrings
  - latest-git-tag
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
        remove_empty_space: true

repo_url: https://github.com/seapagan/py-maker
repo_name: seapagan/py-maker

markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: false
      auto_title: false
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - css/extra.css

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Configuration: configuration.md
  - Templates:
      - Internal Template: template/internal.md
      - Modifying: template/modify.md
      - Replacing: template/replace.md
  - Task Runner: tasks.md
  - Future Plans: future-plans.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - License: license.md
